import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        // New design system
        surface: "#0b0e11",
        "surface-dim": "#0b0e11",
        "surface-bright": "#282d31",
        "surface-container": "#161a1e",
        "surface-container-low": "#101417",
        "surface-container-high": "#1c2024",
        "surface-container-highest": "#22262b",
        "surface-container-lowest": "#000000",
        "on-surface": "#f8f9fe",
        "on-surface-variant": "#a9abaf",
        "inverse-on-surface": "#535559",
        "inverse-surface": "#f8f9fe",
        "outline": "#737679",
        "outline-variant": "#45484c",
        primary: "#ff8c94",
        "primary-dim": "#e80346",
        "primary-fixed": "#ff7481",
        "primary-fixed-dim": "#ff576d",
        "primary-container": "#ff7481",
        "on-primary": "#640019",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#4e0011",
        "on-primary-fixed-variant": "#5f0017",
        "inverse-primary": "#bf0038",
        secondary: "#fc81aa",
        "secondary-dim": "#ef779f",
        "secondary-fixed": "#ffc1d1",
        "secondary-fixed-dim": "#ffacc4",
        "secondary-container": "#822048",
        "on-secondary": "#59002b",
        "on-secondary-fixed": "#690935",
        "on-secondary-fixed-variant": "#8f2a52",
        "on-secondary-container": "#ffbfd0",
        tertiary: "#bd99ff",
        "tertiary-dim": "#b08af7",
        "tertiary-fixed": "#c1a0ff",
        "tertiary-fixed-dim": "#b58ffc",
        "tertiary-container": "#b08af7",
        "on-tertiary": "#3a097c",
        "on-tertiary-fixed": "#210050",
        "on-tertiary-fixed-variant": "#481f89",
        "on-tertiary-container": "#2c0064",
        background: "#0b0e11",
        "on-background": "#f8f9fe",
        error: "#ff7351",
        "error-dim": "#d53d18",
        "error-container": "#b92902",
        "on-error": "#450900",
        "on-error-container": "#ffd2c8",
        "surface-tint": "#ff8c94",
        "surface-variant": "#22262b",

        // Legacy tokens kept for other pages
        bg: {
          base: "#0b0e11",
          card: "#161a1e",
          elevated: "#1c2024",
          hover: "#22262b",
        },
        brand: {
          DEFAULT: "#ff8c94",
          light: "#ffaab0",
          dark: "#e86870",
          glow: "rgba(255, 140, 148, 0.3)",
        },
        accent: {
          pink: "#fc81aa",
          cyan: "#06b6d4",
          amber: "#f59e0b",
        },
        text: {
          base: "#f8f9fe",
          muted: "#a9abaf",
          subtle: "#737679",
          disabled: "#45484c",
        },
      },
      borderColor: {
        subtle: "#22262b",
        brand: "#ff8c94",
      },
      backgroundImage: {
        "hero-gradient": "linear-gradient(135deg, #0b0e11 0%, #1a0a1e 50%, #0b0e11 100%)",
        "card-gradient": "linear-gradient(180deg, transparent 0%, rgba(11,14,17,0.9) 100%)",
        "brand-gradient": "linear-gradient(135deg, #ff8c94, #fc81aa)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 1.5s infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: { "0%": { transform: "translateY(20px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.875rem",
        "2xl": "1.125rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
